dataset:
  folder: "data/" # gen_data
  n_episode: 1 #2000
  n_timestep: 10 #10
  obj: "shirt" 
  wkspc_w: 4.0
  headless: False 
  robot_type: 'xarm6' 
  camera_view: 1 # 0, 1, 2, 3, 4
  camera_radius: 5.5
