dataset:
  folder: "/mnt/sda/data" #'data_dense' #"/media/baoyu/sumsung/granular"
  n_worker: 25
  n_episode: 25
  n_timestep: 10
  obj: "carrots" 
  wkspc_w: 2.5
  headless: True
  robot_type: 'xarm6' 
  cont_motion: False
  camera_view: 1 # 0, 1, 2, 3, 4
  gripper: False
  grasp: False
  physics: "random" # "random" or "grid"
  fps: True
