dataset:
  folder: "data_dense/" # gen_data
  n_worker: 5
  n_episode: 10 #2000
  n_timestep: 1 # tshirt: 5
  obj: "rope" 
  wkspc_w: 4.0
  headless: True
  robot_type: 'xarm6' 
  camera_view: 1 # 0, 1, 2, 3, 4
  camera_radius: 5.5
  dt: 0.1
  gripper: False
