dataset:
  folder: 'data_dense' #"/media/baoyu/sumsung/rope_2" 
  n_worker: 6
  n_episode: 1 #2000
  n_timestep: 1
  obj: "rope" 
  wkspc_w: 4.0
  headless: False
  robot_type: 'xarm6' 
  cont_motion: False
  camera_view: 2 # 0, 1, 2, 3, 4
  camera_radius: 5.5
  dt: 0.1
  gripper: True
  grasp: True
  init: False
