dataset:
  folder: /media/baoyu/sumsung/rope_2 #'data_dense' #"/media/baoyu/sumsung/rope_2" 
  n_worker: 40
  n_episode: 40
  n_timestep: 20
  obj: "rigid_objects" 
  wkspc_w: 4.0
  headless: True
  robot_type: 'xarm6' 
  cont_motion: False
  camera_view: 1 # 0, 1, 2, 3, 4
  camera_radius: 5.5
  dt: 0.1
  gripper: False
  grasp: False
