dataset:
  folder: "/mnt/sda/data" #'data_dense' #"/media/baoyu/sumsung/granular"
  n_worker: 10
  n_episode: 10
  n_timestep: 5
  obj: "cloth" 
  wkspc_w: 4.0
  headless: True
  robot_type: 'xarm6' 
  cont_motion: False
  camera_view: 1 # 0, 1, 2, 3, 4
  gripper: True
  grasp: True
  physics: "random" # "random" or "grid"
  fps: True
  fps_number: 2000
